name: ClashBerry - Discord

on:
  workflow_dispatch:

run-name: "Updated: ${{ github.ref != '' && github.sha != '' && github.event.head_commit.modified[0] || github.event.commits[0].modified[0] }}"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read 

    steps:
      - uses: actions/checkout@v4

      - name: Get latest change
        id: files
        run: |
          git fetch --prune --unshallow
          FILE=$(git diff-tree --no-commit-id --name-only -r HEAD | head -1)
          echo "changed_file=${FILE}" >> $GITHUB_OUTPUT
          echo "GITHUB_RUN_NAME=Updated: ${FILE}" >> $GITHUB_ENV

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write 
      contents: read 

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8E26057F56BE4F5E9332B68850DFDB77 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B95FD9B9E0CE445798B437ADD91E0AD9 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1FF64D47426D441AB67A2A6DCA279C89 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'ClashBerryDiscord'
          slot-name: 'Production'